### ISSUE TITLE
Please add button for VSCode activity bar

### ISSUE THREAD

**Issue by kagarlickij** [fabiospampinato/vscode-open-in-gittower#2]
It would be nice to have a button on activity bar like e.f. gitlens has

**Comment by fabiospampinato** [comment]
What for? We are not contributing any views.

**Comment by kitschpatrol** [comment]
In case anyone else who wanted a button finds this issue, I've implemented it as a [separate extension](https://marketplace.visualstudio.com/items?itemName=kitschpatrol.open-in-git-tower-button), using the same approach as the [vscode-open-in-github-button](https://github.com/antfu/vscode-open-in-github-button).

(Thanks Fabio for doing the heavy lifting here with your extension — I'd offer a PR instead but [I can tell](https://github.com/fabiospampinato/vscode-open-in-github/issues/23) you're probably not a big fan of these sorts of buttons 😅.)
